
name: Delete PR env when PR is closed

on:
  pull_request:
    branches:
      - main
    types: [closed]

concurrency: 
  group: ci-${{ github.event.number }}
  cancel-in-progress: true
permissions:
    id-token: write
env:
  WEBAPP_NAME: apitestcole2
  RESOURCE_GROUP: appsvc_linux_centralus_basic
  SLOT_NAME: pr-${{ github.event.pull_request.title }}


jobs:
  delete-slot:
    runs-on: ubuntu-latest
    environment:
      name: 'Azure-Credential-ENV'
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    
    - name: Delete slot on staging site
      run: az webapp deployment slot delete --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME
    
    - name: DELETE Azure OIDC Federated Token for Temporary PR ENV in App Registration
      id: OIDCTOKEN
      run: | 
        az ad app federated-credential delete \
        --id 0636d7e0-ff77-459e-ae19-4bce311b1df9 \
        --federated-credential-id  PR-${{ github.event.pull_request.title }}

  delete-deployment:
    runs-on: ubuntu-latest
    needs: [delete-slot]

    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: "PR-${{ github.event.pull_request.title }}"
          onlyRemoveDeployments: true
        