
name: Delete PR env when PR is closed

on:
  pull_request:
    branches:
      - main
    types: [closed]

concurrency: 
  group: ci-${{ github.event.number }}
  cancel-in-progress: true

env:
  WEBAPP_NAME: apitestcole2
  RESOURCE_GROUP: appsvc_linux_centralus_basic
  SLOT_NAME: pr-${{ github.event.pull_request.title }}

jobs:
  delete-slot:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    
    - name: Delete slot on staging site
      run: az webapp deployment slot delete --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME

  delete-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v2.0.1
        with:
          environment: "PR-${{ github.event.pull_request.title }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyRemoveDeployments: true