
name: Delete PR env when PR is closed

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

concurrency: 
  group: ci-${{ github.event.number }}
  cancel-in-progress: true
env:
  WEBAPP_NAME: apitestcole2
  RESOURCE_GROUP: appsvc_linux_centralus_basic
  SLOT_NAME: pr-${{ github.event.pull_request.title }}


jobs:

  delete-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete Deployment Environment
        uses: strumwolf/delete-deployment-environment@v2.0.1
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: PR-feature-deletetest 
          onlyRemoveDeployments: true
        