name: Deploy PR to staging env

on:
  pull_request:
    branches:
    - main

concurrency: ci-${{ github.event.number }}
permissions:
  id-token: write
  contents: read

env:
  WEBAPP_NAME: apitestcole2
  RESOURCE_GROUP: appsvc_linux_centralus_basic
  SLOT_NAME: pr-${{ github.event.number }}
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v1

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Node Dependencies
      run: |
        npm install

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: gettapevents-server
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  
  set-up-test-env:
    name: Create test env
    runs-on: ubuntu-latest

    steps:
    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create Azure OIDC Federated Token for Temporary PR ENV in App Registartion
      run: | 
        az ad app federated-credential create --id 0636d7e0-ff77-459e-ae19-4bce311b1df9 --parameters \
      "{                                                                                        
      \"name\":\"TEMP \",
      \"issuer\":\"https://token.actions.githubusercontent.com\",
      \"subject\":\"repo:Trackonomy/env-protection-github:environment:te\",
      \"description\":\"TempToken for \",
      \"audiences\": [ \"api://AzureADTokenExchange\" ]
      }" 

    - name: Create slot on staging site
      run: az webapp deployment slot create --resource-group $RESOURCE_GROUP  --name $WEBAPP_NAME --slot $SLOT_NAME

  deploy:
    name: Deploy to test env
    runs-on: ubuntu-latest
    needs: [build, set-up-test-env]
    environment:
      name: "PR #${{ github.event.number }}"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      pull-requests: write
      id-token: write
      contents: read

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: gettapevents-server

    - name: 'Az CLI login using OIDC'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Deploy to slot on staging site
      uses: azure/webapps-deploy@v1
      id: deploy-to-webapp
      with: 
        app-name: ${{ env.WEBAPP_NAME }}
        slot-name:  ${{ env.SLOT_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Comment on PR with the preview link
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          ## Preview link: https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
          
          - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
          - The preview link is shareable, but will be deleted when the pull request is merged or closed.
          > *This is an automated message.*
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'