on:
  pull_request:
    branches:
    - main

jobs:
  title-check:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: 'https://${{ env.WEBAPP_NAME }}.azurewebsites.net/'
    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az commands'
        run: |
          az account show
          az group list
          az ad app federated-credential create --id 0636d7e0-ff77-459e-ae19-4bce311b1df9 --parameters \
          "{\"name\":\"PR:1\",
          \"issuer\":\"https://token.actions.githubusercontent.com\",
          \"subject\":\"repo:Trackonomy/env-protection-github:environment:PR:1\",
          \"description\":\"TempToken for \",
          \"audiences\": [ \"api://AzureADTokenExchange\" ]
          }"  
