name: 'PR Title Checker'
on: 
  pull_request:
    branches:
      - main

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Force Close Pull Request'
        uses: peter-evans/close-pull@v2
        with:
          pull-request-number: 8
          comment: Auto-closing pull request
          delete-branch: false
