name: 'PR Title Checker'
on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Title Check
        uses: naveenk1223/action-pr-title@master
        id: titlecheck
        with:
          regex: '/^\S*$/' # Regex the title should match.
          allowed_prefixes: 'feature,fix,bugfix,patch,enhancement,hotfix' # title should start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 20 # Max length of the title

      # runs if previous jobs failed and test-app was not successful (failure/cancelled)
      - name: Close Pull Request and Comment
        if: failure() && steps.titlecheck.outcome != 'success'
        uses: peter-evans/close-pull@v2
        with:
          pull-request-number: ${{ github.event.number }}
          comment: |
            ## Preview link: https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net 
            
            - Your changes have been deployed to the preview site. The preview site will update as you add more commits to this branch.
            - The preview link is shareable, but will be deleted when the pull request is merged or closed.
            > *This is an automated message.*
          delete-branch: false