name: 'PR Title Checker'
on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Title Check
        uses: naveenk1223/action-pr-title@master
        id: titlecheck
        with:
          regex: '^[a-zA-Z0-9\*\!\\?\(\)]{5,20}$' # Regex the title should match.
          allowed_prefixes: 'feature,fix,bugfix,patch,enhancement,hotfix' # title should start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 20 # Max length of the title

      # runs if previous jobs failed and test-app was not successful (failure/cancelled)
      - name: Close Pull Request and Comment
        if: failure() && steps.titlecheck.outcome != 'success'
        uses: peter-evans/close-pull@v2
        with:
          pull-request-number: ${{ github.event.number }}
          comment: |
            ## Pull Request Has Been Closed... Title <${{ github.event.pull_request.title }}> is invalid or Not Authorized 
            
            - No Spaces in PR Title
            - Minimum Length of Title is 5
            - Maximum Length of Title is 20
            - PR Must Have one of the Following PREFIXES: [feature,fix,bugfix,patch,enhancement,hotfix]
            > *This is an automated message.*
          delete-branch: false